CREATE DATABASE IF NOT EXISTS agenda;
USE agenda;

CREATE TABLE IF NOT EXISTS PIEZAS (
  CVE_PIEZA INT NOT NULL AUTO_INCREMENT,
  NOMBRE_PIEZA VARCHAR(10) NULL,
  MEDIDAS VARCHAR(10) NULL,
  PRIMARY KEY (CVE_PIEZA)
);

CREATE TABLE IF NOT EXISTS USUARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  CORREO VARCHAR(50) NOT NULL,
  CLAVE VARCHAR(10) NULL,
  NOMBRE VARCHAR(20) NULL,
  APELLIDO_PATERNO VARCHAR(20) NULL,
  APELLIDO_MATERNO VARCHAR(20) NULL,
  PUESTO VARCHAR(50) NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
  ID_CTE INT NOT NULL AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  NOMBRE_CTE VARCHAR(20) NULL,
  APELLIDO_PATERNO_CTE VARCHAR(20) NULL,
  APELLIDO_MATERNO_CTE VARCHAR(20) NULL,
  EMPRESA VARCHAR(50) NULL,
  RFC VARCHAR(13) NULL,
  TELEFONO VARCHAR(10) NULL,
  CORREO_CTE VARCHAR(50) NULL,
  PRIMARY KEY (ID_CTE),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS EVENTOS (
  CVE_EVENTO INT NOT NULL AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  TITULO VARCHAR(20) NULL,
  FECHA DATE NULL,
  HORA TIME NULL,
  DESCRIPCION TEXT NULL,
  PRIMARY KEY (CVE_EVENTO),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
  CVE_PEDIDO INT NOT NULL AUTO_INCREMENT,
  PIEZAS_CVE_PIEZA INT NOT NULL,
  CLIENTES_ID_CTE INT NOT NULL,
  CANTIDAD_PIEZAS INT NULL,
  FECHA_RECIBIDO DATE NULL,
  FECHA_ENTREGA DATE NULL,
  PRECIO_FINAL DECIMAL(10,2) NULL,
  PRIMARY KEY (CVE_PEDIDO),
  FOREIGN KEY (PIEZAS_CVE_PIEZA) REFERENCES PIEZAS(CVE_PIEZA),
  FOREIGN KEY (CLIENTES_ID_CTE) REFERENCES CLIENTES(ID_CTE)
);

CREATE TABLE IF NOT EXISTS FACTURAS (
  CVE_FACTURA INT NOT NULL AUTO_INCREMENT,
  CVE_PEDIDO INT NOT NULL,
  FECHA_FACTURA DATE NULL,
  CANTIDAD_TOTAL DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (CVE_FACTURA),
  FOREIGN KEY (CVE_PEDIDO) REFERENCES PEDIDOS(CVE_PEDIDO)
);
